apiVersion: apps/v1
kind: Deployment
metadata:
  name: height-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: height-app
  template:
    metadata:
      labels:
        app: height-app
    spec:
      containers:
      - name: height-app
        image: kubectl set image deployment/height-app height-app=$IMAGE --record
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
