name: Deploy to Minikube on GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Install gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: your-gcp-project-id

    - name: SSH and deploy (inline script)
      run: |
        gcloud compute ssh murtazabilalqasim@l00187987-node1 \
          --zone=europe-west2-c \
          --command="bash -c '
            set -e
            cd mlops_project

            echo Pulling latest code...
            git pull origin main

            echo Building Docker image...
            docker build -t height-app:latest .

            echo Loading image into Minikube...
            minikube image load height-app:latest

            echo Deploying to Kubernetes...
            kubectl delete deployment height-app --ignore-not-found
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml
          '"
