name: Deploy to Minikube on GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Install gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: healthy-highway-453410-r7

    - name: SSH and run deploy script on VM
      run: |
        gcloud compute ssh murtazabilalqasim@l00187987-node1 \
          --zone=europe-west2-c \
          --command="bash /home/murtazabilalqasim/mlops_project/deploy.sh"