name: CD to Minikube on GCP VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via SSH to GCP VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 35.246.14.225
          username: murtazabilalqasim@35.246.14.225
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            cd mlops_project
            git pull origin main

            eval $(minikube docker-env)

            python3 train.py
            docker build -t height-app:latest .
            minikube image load height-app:latest

            kubectl delete deployment height-app --ignore-not-found
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml
