name: Deploy to Minikube on GCP VM

on:
  push:
    branches:
      - main

jobs:
  mlops_Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: build joblib
      run: python3 model.py
    - name: Run tests
      run: pytest tests/

  deploy:
    needs: mlops_Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Install gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: your-gcp-project-id

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image with tags
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/height-app
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)

        docker build -t $IMAGE_NAME:latest \
                     -t $IMAGE_NAME:${{ github.ref_name }} \
                     -t $IMAGE_NAME:${{ github.ref_name }}-$SHORT_SHA .

        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ github.ref_name }}
        docker push $IMAGE_NAME:${{ github.ref_name }}-$SHORT_SHA

    - name: SSH and deploy (inline script)
      run: |
        gcloud compute ssh murtazabilalqasim@l00187987-node1 \
          --zone=europe-west2-c \
          --command="
              cd /home/murtazabilalqasim/ && \
              rm -rf mlops_project && \
              git clone https://github.com/MBDogar/mlops_project.git && \
              cd mlops_project/k8s && \
              /usr/local/bin/minikube kubectl -- delete -f ./deployment.yaml || true && \
              sleep 5 && \
              /usr/local/bin/minikube kubectl -- apply -f ./deployment.yaml"
